// Configuration.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

class Configuration {
    
    public static var dateFormat = "yyyy-MM-dd'T'HH:mm:ss.SSSZZZZZ"
}
